import { useState } from "react";
import JargonGlossary from "./JargonGlossary";

// Plain-language definitions for every jargon term used across the KeyForge UI.
// One short sentence per term, no other jargon nested inside.
// Keys are normalized to lower-case; lookups normalize the incoming term too.
export const JARGON = {
  totp: "A six-digit code that changes every 30 seconds, generated by an app on your phone like Google Authenticator. It is used as a second factor on top of your password.",
  mfa: "Multi-factor authentication: signing in requires both your password and a second code from your phone, so a stolen password alone is not enough.",
  kms: "A Key Management Service: a separate, hardened vault (such as one provided by AWS, GCP, or Azure) that protects the master key KeyForge uses to lock and unlock your stored credentials.",
  ttl: "Time-to-live: how long something is allowed to stay valid before it expires. A 3600-second TTL means it stops working one hour after it was created.",
  cidr: "A way to write a range of IP addresses as a single line, for example 192.168.1.0/24 means every address from 192.168.1.0 through 192.168.1.255.",
  "envelope encryption": "A two-layer locking system: each credential is locked with its own key, and that key is itself locked with a master key kept somewhere even safer. Compromising one credential cannot leak the others.",
  envelope: "A two-layer locking system: each credential is locked with its own key, and that key is itself locked with a master key kept somewhere even safer. Compromising one credential cannot leak the others.",
  dek: "Data Encryption Key: the inner key that actually scrambles a single credential's data. Each credential gets its own.",
  kek: "Key Encryption Key: the outer master key that locks all the smaller per-credential keys. It lives in your KMS so it never sits next to the data it protects.",
  pat: "Personal Access Token: a long random string a service like GitHub generates and treats as if it were your password for that account, scoped to specific permissions.",
  oauth: "A standard handshake that lets you grant an app limited access to your account on another service (like GitHub or Google) without ever giving it your real password.",
  jwt: "A signed, tamper-proof packet of information your browser carries to prove who you are on every request, so the server does not have to ask you to log in each time.",
  hmac: "A short cryptographic stamp added to a message that lets the receiver confirm the message really came from the expected sender and was not changed in transit.",
  rbac: "Role-Based Access Control: instead of granting each person individual permissions, you put them in roles like 'Read', 'Use', 'Manage', or 'Admin' and the role decides what they can do.",
  "audit chain": "A tamper-evident log where every entry is cryptographically linked to the one before it, so any later edit or deletion is detectable.",
  fingerprint: "A short, unique label calculated from a credential's contents. Two different credentials produce different fingerprints, but the fingerprint never reveals the credential itself.",
  fernet: "A specific, well-vetted recipe for symmetric encryption used by KeyForge to scramble credential data before it touches the database.",
};

const lookup = (term) => {
  if (!term) return null;
  const key = String(term).toLowerCase().trim();
  if (JARGON[key]) return { key, definition: JARGON[key] };
  // Allow callers to pass already-uppercased acronyms or longer phrases; try collapsed match.
  const collapsed = key.replace(/\s+/g, " ");
  if (JARGON[collapsed]) return { key: collapsed, definition: JARGON[collapsed] };
  return null;
};

const JargonTerm = ({ term, children }) => {
  const [hovered, setHovered] = useState(false);
  const [focused, setFocused] = useState(false);
  const [glossaryOpen, setGlossaryOpen] = useState(false);
  const entry = lookup(term);

  // If we do not have a definition, render the children (or term) verbatim with no wrapper.
  if (!entry) {
    return <>{children ?? term}</>;
  }

  const visible = hovered || focused;
  const label = children ?? term;

  return (
    <>
      <span
        className="relative inline-block"
        onMouseEnter={() => setHovered(true)}
        onMouseLeave={() => setHovered(false)}
        onFocus={() => setFocused(true)}
        onBlur={() => setFocused(false)}
      >
        <span
          tabIndex={0}
          role="button"
          aria-describedby={`jargon-tip-${entry.key.replace(/\s+/g, "-")}`}
          className="border-b border-dotted border-gray-400 cursor-help focus:outline-none focus:ring-1 focus:ring-indigo-400 rounded-sm"
        >
          {label}
        </span>
        {visible && (
          <span
            id={`jargon-tip-${entry.key.replace(/\s+/g, "-")}`}
            role="tooltip"
            className="absolute z-50 left-0 top-full mt-1 w-72 p-3 bg-gray-900 text-white text-xs rounded-md shadow-lg normal-case font-normal"
          >
            <span className="block mb-2 leading-snug">{entry.definition}</span>
            <button
              type="button"
              onClick={(e) => {
                e.preventDefault();
                e.stopPropagation();
                setGlossaryOpen(true);
              }}
              className="text-indigo-300 hover:text-indigo-200 underline text-xs"
            >
              Learn more
            </button>
          </span>
        )}
      </span>
      {glossaryOpen && (
        <JargonGlossary
          isOpen={glossaryOpen}
          onClose={() => setGlossaryOpen(false)}
          initialTerm={entry.key}
        />
      )}
    </>
  );
};

export default JargonTerm;
